
TREACHERY_CARDS = [
    "Baliset",
    "Crysknife",
    "Chaumas",
    "Chaumurky",
    "Cheap-Hero/Heroine",
    "Cheap-Hero/Heroine",
    "Cheap-Hero/Heroine",
    "Elacca-Drug",
    "Family-Atomics",
    "Gom-Jabbar",
    "Harj",
    "Jubba Cloak",
    "Karama",
    "Karama",
    "Kulon",
    "La-la-la!",
    "Lasgun",
    "Maula-Pistol",
    "Shield",
    "Shield",
    "Shield",
    "Shield",
    "Snooper",
    "Snooper",
    "Snooper",
    "Snooper",
    "Slip Tip",
    "Stunner",
    "Tleilaxu-Ghola",
    "Trip-to-Gamont",
    "Truthtrance",
    "Truthtrance",
    "Weather-Control"
]
