#! /usr/bin/env python3
import os

from PIL import Image

BOXES = [
    (38, 38, 412, 562),
    (38, 638, 412, 1162),
    (488, 38, 862, 562),
    (488, 638, 862, 1162),
    (938, 38, 1312, 562),
    (938, 638, 1312, 1162),
]


def crop_cards(path):
    im = Image.open(path)
    file, ext = os.path.splitext(path)
    for i, box in enumerate(BOXES):
        im2 = im.crop(box)
        im2.save("{}_{}.png".format(file, i), "PNG")


for i in range(5, 6):
    path = "resources/cards_uncut/spice_{}.png".format(i)
    crop_cards(path)


for i in range(5, 6):
    path = "resources/cards_uncut/traitors_{}.png".format(i)
    crop_cards(path)


for i in range(9, 10):
    path = "resources/cards_uncut/treachery_{}.png".format(i)
    crop_cards(path)
