from dune.state import State

SPACES = [
    ('Arsunt', 'sand', None, None, (10, 11)),
    ('Basin', 'sand', None, None, (8,)),
    ('Bight-of-the-Cliff', 'sand', None, None, (13, 14)),
    ('Broken-Land', 'sand', 11, 8, (10, 11)),
    ('Cielago-Depression', 'sand', None, None, (0, 1, 2)),
    ('Cielago-East', 'sand', None, None, (2, 3)),
    ('Cielago-North', 'sand', 2, 8, (0, 1, 2)),
    ('Cielago-South', 'sand', 1, 12, (1, 2)),
    ('Cielago-West', 'sand', None, None, (0, 17)),
    ('Funeral-Plain', 'sand', 14, 6, (14,)),
    ('Gara-Kulon', 'sand', None, None, (7,)),
    ('Habbanya-Erg', 'sand', 15, 8, (15, 16)),
    ('Habbanya-Ridge-Flat', 'sand', 17, 10, (16, 17)),
    ('Hagga-Basin', 'sand', 12, 6, (11, 12)),
    ('Harg-Pass', 'sand', None, None, (3, 4)),
    ('Hole-in-the-Rock', 'sand', None, None, (8,)),
    ('Meridian', 'sand', None, None, (0, 1)),
    ('Old-Gap', 'sand', 9, 6, (8, 9, 10)),
    ('Red-Chasm', 'sand', 6, 8, (6,)),
    ('Rock-Outcroppings', 'sand', 13, 6, (12, 13)),
    ('Sihaya-Ridge', 'sand', 8, 6, (8,)),
    ('South-Mesa', 'sand', 4, 10, (3, 4, 5)),
    ('Great-Flat', 'sand', 14, 10, (14,)),
    ('Greater-Flat', 'sand', None, None, (15,)),
    ('Minor-Erg', 'sand', 7, 8, (4, 5, 6, 7)),
    ('Tsimpo', 'sand', None, None, (10, 11, 12)),
    ('Wind-Pass', 'sand', None, None, (13, 14, 15, 16)),
    ('Wind-Pass-North', 'sand', 16, 6, (16, 17)),
    ('Polar-Sink', 'sink', None, None, (-1,)),
    ('False-Wall-East', 'rock', None, None, (4, 5, 6, 7, 8)),
    ('False-Wall-South', 'rock', None, None, (3, 4)),
    ('False-Wall-West', 'rock', None, None, (15, 16, 17)),
    ('Pasty-Mesa', 'rock', None, None, (4, 5, 6, 7)),
    ('Plastic-Basin', 'rock', None, None, (11, 12, 13)),
    ('Rim-Wall-West', 'rock', None, None, (8,)),
    ('Shield-Wall', 'rock', None, None, (7, 8)),
    ('Habbanya-Sietch', 'stronghold', None, None, (16,)),
    ('Sietch-Tabr', 'stronghold', None, None, (13,)),
    ('Tueks-Sietch', 'stronghold', None, None, (4,)),
    ('Arrakeen', 'shielded-stronghold', None, None, (9,)),
    ('Carthag', 'shielded-stronghold', None, None, (10,)),
    ('Imperial-Basin', 'shielded-sand', None, None, (8, 9, 10))
]

EDGES = [
    (('Arsunt', 10), ('Carthag', 10)),
    (('Arsunt', 10), ('Imperial-Basin', 10)),
    (('Arsunt', 10), ('Polar-Sink', -1)),
    (('Arsunt', 10), ('Hagga Basin', 11)),
    (('Arsunt', 11), ('Polar-Sink', -1)),
    (('Arsunt', 11), ('Hagga Basin', 11)),
    (('Arsunt', 11), ('Hagga Basin', 12)),
    (('Basin', 8), ('Old-Gap', 8)),
    (('Basin', 8), ('Rim-Wall-West', 8)),
    (('Basin', 8), ('Hole-in-the-Rock', 8)),
    (('Basin', 8), ('Sihaya-Ridge', 8)),
    (('Bight-of-the-Cliff', 13), ('Rock-Outcroppings', 13)),
    (('Bight-of-the-Cliff', 13), ('Sietch-Tabr', 13)),
    (('Bight-of-the-Cliff', 13), ('Plastic-Basin', 13)),
    (('Bight-of-the-Cliff', 14), ('Funeral-Plain', 14)),
    (('Broken-Land', 10), ('Old-Gap', 10)),
    (('Broken-Land', 10), ('Tsimpo', 10)),
    (('Broken-Land', 11), ('Tsimpo', 11)),
    (('Broken-Land', 11), ('Rock-Outcroppings', 12)),
    (('Broken-Land', 11), ('Plastic-Basin', 11)),
    (('Cielago-Depression', 0), ('Cielago-North', 0)),
    (('Cielago-Depression', 0), ('Meridian', 0)),
    (('Cielago-Depression', 0), ('Cielago-West', 0)),
    (('Cielago-Depression', 1), ('Cielago-North', 1)),
    (('Cielago-Depression', 1), ('Meridian', 1)),
    (('Cielago-Depression', 1), ('Cielago-South', 1)),
    (('Cielago-Depression', 2), ('Cielago-North', 2)),
    (('Cielago-Depression', 2), ('Cielago-South', 2)),
    (('Cielago-Depression', 2), ('Cielago-East', 2)),
    (('Cielago-East', 2), ('Cielago-South', 2)),
    (('Cielago-East', 2), ('Cielago-North', 2)),
    (('Cielago-East', 3), ('South-Mesa', 3)),
    (('Cielago-East', 3), ('False-Wall-South', 3)),
    (('Cielago-North', 0), ('Wind-Pass-North', 17)),
    (('Cielago-North', 0), ('Cielago-West', 17)),
    (('Cielago-North', 0), ('Cielago-West', 0)),
    (('Cielago-North', 0), ('Polar-Sink', -1)),
    (('Cielago-North', 1), ('Polar-Sink', -1)),
    (('Cielago-North', 2), ('Polar-Sink', -1)),
    (('Cielago-North', 2), ('Harg-Pass', 3)),
    (('Cielago-North', 2), ('False-Wall-South', 3)),
    (('Cielago-South', 1), ('Meridian', 1)),
    (('Cielago-West', 17), ('Wind-Pass', 16)),
    (('Cielago-West', 17), ('Wind-Pass-North', 17)),
    (('Cielago-West', 17), ('False-Wall-West', 17)),
    (('Cielago-West', 17), ('Habbanya-Ridge-Flat', 17)),
    (('Cielago-West', 0), ('Meridian', 0)),
    (('Funeral-Plain', 14), ('Plastic-Basin', 13)),
    (('Funeral-Plain', 14), ('Great-Flat', 14)),
    (('Gara-Kulon', 7), ('Sihaya-Ridge', 8)),
    (('Gara-Kulon', 7), ('Shield-Wall', 7)),
    (('Gara-Kulon', 7), ('Pasty-Mesa', 7)),
    (('Habbanya-Erg', 15), ('Greater-Flat', 15)),
    (('Habbanya-Erg', 15), ('Habbanya-Ridge-Flat', 16)),
    (('Habbanya-Erg', 16), ('Habbanya-Ridge-Flat', 16)),
    (('Habbanya-Erg', 16), ('False-Wall-West', 16)),
    (('Habbanya-Ridge-Flat', 16), ('False-Wall-West', 16)),
    (('Habbanya-Ridge-Flat', 16), ('Habbanya-Sietch', 16)),
    (('Habbanya-Ridge-Flat', 17), ('Habbanya-Sietch', 16)),
    (('Habbanya-Ridge-Flat', 17), ('False-Wall-West', 17)),
    (('Habbanya-Ridge-Flat', 17), ('Meridian', 0)),
    (('Hagga-Basin', 11), ('Carthag', 10)),
    (('Hagga-Basin', 11), ('Tsimpo', 11)),
    (('Hagga-Basin', 12), ('Polar-Sink', -1)),
    (('Hagga-Basin', 12), ('Tsimpo', 12)),
    (('Hagga-Basin', 12), ('Plastic-Basin', 12)),
    (('Hagga-Basin', 12), ('Plastic-Basin', 13)),
    (('Hagga-Basin', 12), ('Wind-Pass', 13)),
    (('Harg-Pass', 3), ('Polar-Sink', -1)),
    (('Harg-Pass', 3), ('False-Wall-East', 4)),
    (('Harg-Pass', 3), ('False-Wall-South', 3)),
    (('Harg-Pass', 4), ('False-Wall-East', 4)),
    (('Harg-Pass', 4), ('False-Wall-South', 4)),
    (('Harg-Pass', 4), ('Minor-Erg', 4)),
    (('Hole-in-the-Rock', 8), ('Rim-Wall-West', 8)),
    (('Hole-in-the-Rock', 8), ('Imperial-Basin', 8)),
    (('Hole-in-the-Rock', 8), ('Shield-Wall', 8)),
    (('Hole-in-the-Rock', 8), ('Sihaya-Ridge', 8)),
    (('Old-Gap', 8), ('Rim-Wall-West', 8)),
    (('Old-Gap', 9), ('Arrakeen', 9)),
    (('Old-Gap', 9), ('Imperial-Basin', 9)),
    (('Old-Gap', 10), ('Tsimpo', 10)),
    (('Red-Chasm', 6), ('South-Mesa', 5)),
    (('Red-Chasm', 6), ('Pasty-Mesa', 6)),
    (('Rock-Outcroppings', 12), ('Plastic-Basin', 12)),
    (('Rock-Outcroppings', 13), ('Sietch-Tabr', 13)),
    (('Rock-Outcroppings', 13), ('Plastic-Basin', 13)),
    (('Sihaya-Ridge', 8), ('Shield-Wall', 8)),
    (('South-Mesa', 3), ('False-Wall-South', 3)),
    (('South-Mesa', 4), ('False-Wall-South', 4)),
    (('South-Mesa', 4), ('Tueks-Sietch', 4)),
    (('South-Mesa', 4), ('Pasty-Mesa', 4)),
    (('South-Mesa', 5), ('Pasty-Mesa', 5)),
    (('Great-Flat', 14), ('Greater-Flat', 14)),
    (('Great-Flat', 14), ('Wind-Pass', 14)),
    (('Great-Flat', 14), ('Plastic-Basin', 13)),
    (('Greater-Flat', 15), ('Wind-Pass', 15)),
    (('Greater-Flat', 15), ('False-Wall-West', 15)),
    (('Minor-Erg', 4), ('False-Wall-East', 4)),
    (('Minor-Erg', 4), ('False-Wall-South', 4)),
    (('Minor-Erg', 4), ('Pasty-Mesa', 4)),
    (('Minor-Erg', 5), ('False-Wall-East', 5)),
    (('Minor-Erg', 5), ('Pasty-Mesa', 5)),
    (('Minor-Erg', 6), ('Pasty-Mesa', 6)),
    (('Minor-Erg', 6), ('False-Wall-East', 6)),
    (('Minor-Erg', 7), ('False-Wall-East', 7)),
    (('Minor-Erg', 7), ('Pasty-Mesa', 7)),
    (('Minor-Erg', 7), ('Shield-Wall', 7)),
    (('Tsimpo', 10), ('Carthag', 10)),
    (('Tsimpo', 10), ('Imperial-Basin', 10)),
    (('Tsimpo', 11), ('Carthag', 10)),
    (('Tsimpo', 11), ('Plastic-Basin', 11)),
    (('Tsimpo', 12), ('Plastic-Basin', 12)),
    (('Wind-Pass', 13), ('Plastic-Basin', 13)),
    (('Wind-Pass', 13), ('Polar-Sink', -1)),
    (('Wind-Pass', 14), ('Polar-Sink', -1)),
    (('Wind-Pass', 15), ('Polar-Sink', -1)),
    (('Wind-Pass', 15), ('Wind-Pass-North', 16)),
    (('Wind-Pass', 15), ('False-Wall-West', 15)),
    (('Wind-Pass', 16), ('Wind-Pass-North', 16)),
    (('Wind-Pass', 16), ('False-Wall-West', 16)),
    (('Wind-Pass-North', 16), ('Polar-Sink', -1)),
    (('Wind-Pass-North', 17), ('Polar-Sink', -1)),
    (('Polar-Sink', -1), ('False-Wall-East', 4)),
    (('Polar-Sink', -1), ('False-Wall-East', 5)),
    (('Polar-Sink', -1), ('False-Wall-East', 6)),
    (('Polar-Sink', -1), ('False-Wall-East', 7)),
    (('Polar-Sink', -1), ('Imperial-Basin', 8)),
    (('Polar-Sink', -1), ('Imperial-Basin', 9)),
    (('False-Wall-East', 7), ('Shield-Wall', 7)),
    (('False-Wall-East', 8), ('Shield-Wall', 8)),
    (('False-Wall-East', 8), ('Imperial-Basin', 8)),
    (('False-Wall-South', 3), ('Tueks-Sietch', 4)),
    (('False-Wall-South', 4), ('Tueks-Sietch', 4)),
    (('False-Wall-South', 4), ('Pasty-Mesa', 4)),
    (('Pasty-Mesa', 4), ('Tueks-Sietch', 4)),
    (('Pasty-Mesa', 5), ('Tueks-Sietch', 4)),
    (('Pasty-Mesa', 7), ('Shield-Wall', 7)),
    (('Plastic-Basin', 13), ('Sietch-Tabr', 13)),
    (('Rim-Wall-West', 8), ('Arrakeen', 9)),
    (('Rim-Wall-West', 8), ('Imperial-Basin', 8)),
    (('Rim-Wall-West', 8), ('Imperial-Basin', 9)),
    (('Arrakeen', 9), ('Imperial-Basin', 9)),
    (('Carthag', 10), ('Imperial-Basin', 10)),
]


class SpaceState(State):
    def __repr__(self):
        return "<SpaceState {} ({}) >".format(self.name, " ".join(self.forces))

    def __init__(self, name, kind, spice_sector, spice_amount, sectors):
        # Properties
        self.name = name
        self.type = kind
        self.spice_sector = spice_sector
        self.spice_amount = spice_amount
        self.sectors = sectors

        # State
        self.spice = 0
        self.forces = {}
        self.coexist = False
        self.was_coexist = False

    def visible(self, game_state, faction):
        visible = super().visible(game_state, faction)
        visible["name"] = self.name
        visible["type"] = self.type
        visible["spice_sector"] = self.spice_sector
        visible["spice_amount"] = self.spice_amount
        visible["sectors"] = self.sectors
        visible["spice"] = self.spice
        visible["forces"] = self.forces
        visible["coexist"] = self.coexist

        return visible
