from boardzorg.state import State

SPACES = [
    ('Arsunt', 'meadow', None, None, (10, 11)),
    ('Basin', 'meadow', None, None, (8,)),
    ('Bight-of-the-Cliff', 'meadow', None, None, (13, 14)),
    ('Broken-Land', 'meadow', 11, 8, (10, 11)),
    ('Cielago-Depression', 'meadow', None, None, (0, 1, 2)),
    ('Cielago-East', 'meadow', None, None, (2, 3)),
    ('Big-Stones-And-Rox', 'meadow', 2, 8, (0, 1, 2)),
    ('Cielago-South', 'meadow', 1, 12, (1, 2)),
    ('Upper-River', 'meadow', None, None, (0, 17)),
    ('Funeral-Plain', 'meadow', 14, 6, (14,)),
    ('Gara-GorseBush', 'meadow', None, None, (7,)),
    ('Habbanya-Erg', 'meadow', 15, 8, (15, 16)),
    ('Pooh-Trap-For-Heffalumps', 'meadow', 17, 10, (16, 17)),
    ('Rather-Boggy-And-Sad', 'meadow', 12, 6, (11, 12)),
    ('Harg-Pass', 'meadow', None, None, (3, 4)),
    ('Hole-in-the-Woods', 'meadow', None, None, (8,)),
    ('LowerRiver', 'meadow', None, None, (0, 1)),
    ('Old-Gap', 'meadow', 9, 6, (8, 9, 10)),
    ('Red-Chasm', 'meadow', 6, 8, (6,)),
    ('Woods-Outcroppings', 'meadow', 13, 6, (12, 13)),
    ('Sihaya-Ridge', 'meadow', 8, 6, (8,)),
    ('Meadowy-Pit-Where-Roo-Plays', 'meadow', 4, 10, (3, 4, 5)),
    ('My-House', 'meadow', 14, 10, (14,)),
    ('The-Greater-Flat', 'meadow', None, None, (15,)),
    ('Nice-For-Picnick', 'meadow', 7, 8, (4, 5, 6, 7)),
    ('Tsimpo', 'meadow', None, None, (10, 11, 12)),
    ('Crosstern-River', 'meadow', None, None, (13, 14, 15, 16)),
    ('Crosstern-River-North', 'meadow', 16, 6, (16, 17)),
    ('The-North-Pole', 'sink', None, None, (-1,)),
    ('Some-More-Woods', 'woods', None, None, (4, 5, 6, 7, 8)),
    ('Leftern-Woods', 'woods', None, None, (3, 4)),
    ('Where-The-Woozle-Wasnt', 'woods', None, None, (15, 16, 17)),
    ('Six-Pine-Trees', 'woods', None, None, (4, 5, 6, 7)),
    ('Rabbits-Frends-And-Raletions', 'woods', None, None, (11, 12, 13)),
    ('Some-Woods', 'woods', None, None, (8,)),
    ('Bee-Tree', 'woods', None, None, (7, 8)),
    ('Poohs-House', 'house', None, None, (16,)),
    ('Rabbits-House', 'house', None, None, (13,)),
    ('Kangas-House', 'house', None, None, (4,)),
    ('OwlsHouse', 'umbrellaed-house', None, None, (9,)),
    ('PigletsHouse', 'umbrellaed-house', None, None, (10,)),
    ('Eeyores-Gloomy-Place', 'protected-meadow', None, None, (8, 9, 10))
]

EDGES = [
    (('Arsunt', 10), ('PigletsHouse', 10)),
    (('Arsunt', 10), ('Eeyores-Gloomy-Place', 10)),
    (('Arsunt', 10), ('The-North-Pole', -1)),
    (('Arsunt', 10), ('Rather Boggy And Sad', 11)),
    (('Arsunt', 11), ('The-North-Pole', -1)),
    (('Arsunt', 11), ('Rather Boggy And Sad', 11)),
    (('Arsunt', 11), ('Rather Boggy And Sad', 12)),
    (('Basin', 8), ('Old-Gap', 8)),
    (('Basin', 8), ('Some-Woods', 8)),
    (('Basin', 8), ('Hole-in-the-Woods', 8)),
    (('Basin', 8), ('Sihaya-Ridge', 8)),
    (('Bight-of-the-Cliff', 13), ('Woods-Outcroppings', 13)),
    (('Bight-of-the-Cliff', 13), ('Rabbits-House', 13)),
    (('Bight-of-the-Cliff', 13), ('Rabbits-Frends-And-Raletions', 13)),
    (('Bight-of-the-Cliff', 14), ('Funeral-Plain', 14)),
    (('Broken-Land', 10), ('Old-Gap', 10)),
    (('Broken-Land', 10), ('Tsimpo', 10)),
    (('Broken-Land', 11), ('Tsimpo', 11)),
    (('Broken-Land', 11), ('Woods-Outcroppings', 12)),
    (('Broken-Land', 11), ('Rabbits-Frends-And-Raletions', 11)),
    (('Cielago-Depression', 0), ('Big-Stones-And-Rox', 0)),
    (('Cielago-Depression', 0), ('LowerRiver', 0)),
    (('Cielago-Depression', 0), ('Upper-River', 0)),
    (('Cielago-Depression', 1), ('Big-Stones-And-Rox', 1)),
    (('Cielago-Depression', 1), ('LowerRiver', 1)),
    (('Cielago-Depression', 1), ('Cielago-South', 1)),
    (('Cielago-Depression', 2), ('Big-Stones-And-Rox', 2)),
    (('Cielago-Depression', 2), ('Cielago-South', 2)),
    (('Cielago-Depression', 2), ('Cielago-East', 2)),
    (('Cielago-East', 2), ('Cielago-South', 2)),
    (('Cielago-East', 2), ('Big-Stones-And-Rox', 2)),
    (('Cielago-East', 3), ('Meadowy-Pit-Where-Roo-Plays', 3)),
    (('Cielago-East', 3), ('Leftern-Woods', 3)),
    (('Big-Stones-And-Rox', 0), ('Crosstern-River-North', 17)),
    (('Big-Stones-And-Rox', 0), ('Upper-River', 17)),
    (('Big-Stones-And-Rox', 0), ('Upper-River', 0)),
    (('Big-Stones-And-Rox', 0), ('The-North-Pole', -1)),
    (('Big-Stones-And-Rox', 1), ('The-North-Pole', -1)),
    (('Big-Stones-And-Rox', 2), ('The-North-Pole', -1)),
    (('Big-Stones-And-Rox', 2), ('Harg-Pass', 3)),
    (('Big-Stones-And-Rox', 2), ('Leftern-Woods', 3)),
    (('Cielago-South', 1), ('LowerRiver', 1)),
    (('Upper-River', 17), ('Crosstern-River', 16)),
    (('Upper-River', 17), ('Crosstern-River-North', 17)),
    (('Upper-River', 17), ('Where-The-Woozle-Wasnt', 17)),
    (('Upper-River', 17), ('Pooh-Trap-For-Heffalumps', 17)),
    (('Upper-River', 0), ('LowerRiver', 0)),
    (('Funeral-Plain', 14), ('Rabbits-Frends-And-Raletions', 13)),
    (('Funeral-Plain', 14), ('My-House', 14)),
    (('Gara-GorseBush', 7), ('Sihaya-Ridge', 8)),
    (('Gara-GorseBush', 7), ('Bee-Tree', 7)),
    (('Gara-GorseBush', 7), ('Six-Pine-Trees', 7)),
    (('Habbanya-Erg', 15), ('The-Greater-Flat', 15)),
    (('Habbanya-Erg', 15), ('Pooh-Trap-For-Heffalumps', 16)),
    (('Habbanya-Erg', 16), ('Pooh-Trap-For-Heffalumps', 16)),
    (('Habbanya-Erg', 16), ('Where-The-Woozle-Wasnt', 16)),
    (('Pooh-Trap-For-Heffalumps', 16), ('Where-The-Woozle-Wasnt', 16)),
    (('Pooh-Trap-For-Heffalumps', 16), ('Poohs-House', 16)),
    (('Pooh-Trap-For-Heffalumps', 17), ('Poohs-House', 16)),
    (('Pooh-Trap-For-Heffalumps', 17), ('Where-The-Woozle-Wasnt', 17)),
    (('Pooh-Trap-For-Heffalumps', 17), ('LowerRiver', 0)),
    (('Rather-Boggy-And-Sad', 11), ('PigletsHouse', 10)),
    (('Rather-Boggy-And-Sad', 11), ('Tsimpo', 11)),
    (('Rather-Boggy-And-Sad', 12), ('The-North-Pole', -1)),
    (('Rather-Boggy-And-Sad', 12), ('Tsimpo', 12)),
    (('Rather-Boggy-And-Sad', 12), ('Rabbits-Frends-And-Raletions', 12)),
    (('Rather-Boggy-And-Sad', 12), ('Rabbits-Frends-And-Raletions', 13)),
    (('Rather-Boggy-And-Sad', 12), ('Crosstern-River', 13)),
    (('Harg-Pass', 3), ('The-North-Pole', -1)),
    (('Harg-Pass', 3), ('Some-More-Woods', 4)),
    (('Harg-Pass', 3), ('Leftern-Woods', 3)),
    (('Harg-Pass', 4), ('Some-More-Woods', 4)),
    (('Harg-Pass', 4), ('Leftern-Woods', 4)),
    (('Harg-Pass', 4), ('Nice-For-Picnick', 4)),
    (('Hole-in-the-Woods', 8), ('Some-Woods', 8)),
    (('Hole-in-the-Woods', 8), ('Eeyores-Gloomy-Place', 8)),
    (('Hole-in-the-Woods', 8), ('Bee-Tree', 8)),
    (('Hole-in-the-Woods', 8), ('Sihaya-Ridge', 8)),
    (('Old-Gap', 8), ('Some-Woods', 8)),
    (('Old-Gap', 9), ('OwlsHouse', 9)),
    (('Old-Gap', 9), ('Eeyores-Gloomy-Place', 9)),
    (('Old-Gap', 10), ('Tsimpo', 10)),
    (('Red-Chasm', 6), ('Meadowy-Pit-Where-Roo-Plays', 5)),
    (('Red-Chasm', 6), ('Six-Pine-Trees', 6)),
    (('Woods-Outcroppings', 12), ('Rabbits-Frends-And-Raletions', 12)),
    (('Woods-Outcroppings', 13), ('Rabbits-House', 13)),
    (('Woods-Outcroppings', 13), ('Rabbits-Frends-And-Raletions', 13)),
    (('Sihaya-Ridge', 8), ('Bee-Tree', 8)),
    (('Meadowy-Pit-Where-Roo-Plays', 3), ('Leftern-Woods', 3)),
    (('Meadowy-Pit-Where-Roo-Plays', 4), ('Leftern-Woods', 4)),
    (('Meadowy-Pit-Where-Roo-Plays', 4), ('Kangas-House', 4)),
    (('Meadowy-Pit-Where-Roo-Plays', 4), ('Six-Pine-Trees', 4)),
    (('Meadowy-Pit-Where-Roo-Plays', 5), ('Six-Pine-Trees', 5)),
    (('My-House', 14), ('The-Greater-Flat', 15)),
    (('My-House', 14), ('Crosstern-River', 14)),
    (('My-House', 14), ('Rabbits-Frends-And-Raletions', 13)),
    (('The-Greater-Flat', 15), ('Crosstern-River', 15)),
    (('The-Greater-Flat', 15), ('Where-The-Woozle-Wasnt', 15)),
    (('Nice-For-Picnick', 4), ('Some-More-Woods', 4)),
    (('Nice-For-Picnick', 4), ('Leftern-Woods', 4)),
    (('Nice-For-Picnick', 4), ('Six-Pine-Trees', 4)),
    (('Nice-For-Picnick', 5), ('Some-More-Woods', 5)),
    (('Nice-For-Picnick', 5), ('Six-Pine-Trees', 5)),
    (('Nice-For-Picnick', 6), ('Six-Pine-Trees', 6)),
    (('Nice-For-Picnick', 6), ('Some-More-Woods', 6)),
    (('Nice-For-Picnick', 7), ('Some-More-Woods', 7)),
    (('Nice-For-Picnick', 7), ('Six-Pine-Trees', 7)),
    (('Nice-For-Picnick', 7), ('Bee-Tree', 7)),
    (('Tsimpo', 10), ('PigletsHouse', 10)),
    (('Tsimpo', 10), ('Eeyores-Gloomy-Place', 10)),
    (('Tsimpo', 11), ('PigletsHouse', 10)),
    (('Tsimpo', 11), ('Rabbits-Frends-And-Raletions', 11)),
    (('Tsimpo', 12), ('Rabbits-Frends-And-Raletions', 12)),
    (('Crosstern-River', 13), ('Rabbits-Frends-And-Raletions', 13)),
    (('Crosstern-River', 13), ('The-North-Pole', -1)),
    (('Crosstern-River', 14), ('The-North-Pole', -1)),
    (('Crosstern-River', 15), ('The-North-Pole', -1)),
    (('Crosstern-River', 15), ('Crosstern-River-North', 16)),
    (('Crosstern-River', 15), ('Where-The-Woozle-Wasnt', 15)),
    (('Crosstern-River', 16), ('Crosstern-River-North', 16)),
    (('Crosstern-River', 16), ('Where-The-Woozle-Wasnt', 16)),
    (('Crosstern-River-North', 16), ('The-North-Pole', -1)),
    (('Crosstern-River-North', 17), ('The-North-Pole', -1)),
    (('The-North-Pole', -1), ('Some-More-Woods', 4)),
    (('The-North-Pole', -1), ('Some-More-Woods', 5)),
    (('The-North-Pole', -1), ('Some-More-Woods', 6)),
    (('The-North-Pole', -1), ('Some-More-Woods', 7)),
    (('The-North-Pole', -1), ('Eeyores-Gloomy-Place', 8)),
    (('The-North-Pole', -1), ('Eeyores-Gloomy-Place', 9)),
    (('Some-More-Woods', 7), ('Bee-Tree', 7)),
    (('Some-More-Woods', 8), ('Bee-Tree', 8)),
    (('Some-More-Woods', 8), ('Eeyores-Gloomy-Place', 8)),
    (('Leftern-Woods', 3), ('Kangas-House', 4)),
    (('Leftern-Woods', 4), ('Kangas-House', 4)),
    (('Leftern-Woods', 4), ('Six-Pine-Trees', 4)),
    (('Six-Pine-Trees', 4), ('Kangas-House', 4)),
    (('Six-Pine-Trees', 5), ('Kangas-House', 4)),
    (('Six-Pine-Trees', 7), ('Bee-Tree', 7)),
    (('Rabbits-Frends-And-Raletions', 13), ('Rabbits-House', 13)),
    (('Some-Woods', 8), ('OwlsHouse', 9)),
    (('Some-Woods', 8), ('Eeyores-Gloomy-Place', 8)),
    (('Some-Woods', 8), ('Eeyores-Gloomy-Place', 9)),
    (('OwlsHouse', 9), ('Eeyores-Gloomy-Place', 9)),
    (('PigletsHouse', 10), ('Eeyores-Gloomy-Place', 10)),
]


class SpaceState(State):
    def __repr__(self):
        return "<SpaceState {} ({}) >".format(self.name, " ".join(self.forces))

    def __init__(self, name, kind, hunny_sector, hunny_amount, sectors):
        # Properties
        self.name = name
        self.type = kind
        self.hunny_sector = hunny_sector
        self.hunny_amount = hunny_amount
        self.sectors = sectors

        # State
        self.hunny = 0
        self.forces = {}
        self.chill_out = False
        self.was_chill_out = False

    def visible(self, game_state, faction):
        visible = super().visible(game_state, faction)
        visible["name"] = self.name
        visible["type"] = self.type
        visible["hunny_sector"] = self.hunny_sector
        visible["hunny_amount"] = self.hunny_amount
        visible["sectors"] = self.sectors
        visible["hunny"] = self.hunny
        visible["forces"] = self.forces
        visible["chill_out"] = self.chill_out

        return visible
